### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by moxley** [samuelpordeus/vscode-elixir-test#84]
I recently received the update to vscode-elixir-test, and this error happens when I try to run tests:

<img width="582" alt="CleanShot 2023-11-20 at 16 51 46@2x" src="https://github.com/samuelpordeus/vscode-elixir-test/assets/86996/19b127c5-867b-489d-98bd-d1c5b9572790">

In Extension Host:

```
2023-11-20 16:51:39.616 [error] TypeError: Cannot read properties of undefined (reading 'length')
    at mix (/Users/mstratto/.vscode/extensions/samuel-pordeus.elixir-test-1.8.0/src/helpers/mix.js:7:47)
    at Object.testPath (/Users/mstratto/.vscode/extensions/samuel-pordeus.elixir-test-1.8.0/src/helpers/mix.js:36:10)
    at /Users/mstratto/.vscode/extensions/samuel-pordeus.elixir-test-1.8.0/src/commands/runTestFile.js:5:46
    at Object.onTestFile (/Users/mstratto/.vscode/extensions/samuel-pordeus.elixir-test-1.8.0/src/helpers/test.js:39:17)
    at Object.handler (/Users/mstratto/.vscode/extensions/samuel-pordeus.elixir-test-1.8.0/src/commands/runTestFile.js:5:8)
    at /Users/mstratto/.vscode/extensions/samuel-pordeus.elixir-test-1.8.0/src/extension.js:13:25
```

Downgrading to version 1.7.1 resolves the problem.

**Comment by msramos** [comment]
@moxley version `1.8.1` is available for download with this fix. Thanks!
